# Generated by Django 4.1.7 on 2023-03-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('subtitle', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'AppInfo',
            },
        ),
    ]
